-- 코드를 입력하세요
WITH MAXVAL AS(SELECT FOOD_TYPE, MAX(FAVORITES) AS MAXV
FROM REST_INFO A
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC)

SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM MAXVAL A
JOIN REST_INFO B
ON A.MAXV = B.FAVORITES && A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY B.FOOD_TYPE DESC