WITH POSIBBLE AS (SELECT CAR_ID AS P
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
ORDER BY CAR_ID DESC)

SELECT CAR_ID, 
CASE WHEN B.P IS NULL THEN '대여 가능' ELSE '대여중' END AS AVAILABILITY
FROM (SELECT DISTINCT(CAR_ID) FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) A
LEFT JOIN POSIBBLE B
ON A.CAR_ID = B.P
ORDER BY CAR_ID DESC;
