WITH RECURSIVE CTE AS(
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM + 1
    FROM CTE
    WHERE NUM < 23
)

SELECT NUM, COUNT(ANIMAL_ID)
FROM CTE
LEFT JOIN ANIMAL_OUTS 
ON HOUR(DATETIME) = NUM
GROUP BY NUM
ORDER BY NUM