-- 코드를 작성해주세요
WITH RAREITEM AS (SELECT ITEM_ID AS RAREITEM
FROM ITEM_INFO
WHERE RARITY = 'RARE')

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T
ON I.ITEM_ID=T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (SELECT RAREITEM FROM RAREITEM)
ORDER BY I.ITEM_ID DESC;
