WITH CAR AS (
    SELECT CAR_ID, COUNT(*) AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT 
    EXTRACT(MONTH FROM H.START_DATE) AS MONTH,
    H.CAR_ID, 
    COUNT(H.CAR_ID) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN 
    CAR C
ON 
    C.CAR_ID = H.CAR_ID
WHERE 
    H.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 
    EXTRACT(MONTH FROM H.START_DATE), H.CAR_ID
ORDER BY 
    EXTRACT(MONTH FROM H.START_DATE), H.CAR_ID DESC;
