-- 코드를 작성해주세요
WITH MONTHS AS (SELECT MONTH(TIME) AS MONTH
FROM FISH_INFO 
GROUP BY MONTH(TIME)
ORDER BY MONTH(TIME))

SELECT COUNT(*) AS FISH_COUNT, MONTH
FROM MONTHS M
JOIN FISH_INFO I
ON M.MONTH = MONTH(I.TIME)
GROUP BY MONTH
ORDER BY MONTH